---

site_name: 12 Angry Men Dynasty FF
# site_url: https://wwg-internal.github.io/cidr-mkdocs
repo_url: https://github.com/quinnstiegman/12-angry-men-dynasty
repo_name: quinnstiegman/12-angry-men-dynasty
edit_uri: blob/main/docs/
use_directory_urls: false


nav:
    - 🏈 Home: 'index.md'
    - 🚨 Rules: 
      - 📖 Bylaws: 'rules/bylaws.md'
      - 💬 Proposed Changes:  'rules/proposed-changes.md'

theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/favicon.png
    favicon: assets/favicon.png
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye
    palette:

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/lightbulb
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/lightbulb-outline
              name: Switch to light mode

    features:
        # - header.autohide
        - content.action.edit
        - navigation.footer
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow


markdown_extensions:
    - abbr
    - attr_list
    # - pymdownx.emoji:
    #       emoji_index: !!python/name:materialx.emoji.twemoji
    #       emoji_generator: !!python/name:materialx.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.highlight:
          linenums_style: pymdownx-inline
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.tabbed:
          alternate_style: true

extra_css: #
  - styling/extra.css
  - site/assets/stylesheets/glightbox.min.css 

extra_javascript:
  - styling/extra.js

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - site/assets/javascripts/glightbox.min.js


plugins:
    - search
    - inline-svg
    - git-revision-date-localized:
            enable_creation_date: true
    - git-authors
#     - glightbox:
#             touchNavigation: false
#             loop: false
#             effect: zoom
#             slide_effect: slide
#             width: 100%
#             height: 100vh
#             zoomable: false
#             draggable: true
#             skip_classes:
#                   - custom-skip-class-name
#             auto_caption: false
#             caption_position: bottom