name: deploy-website
on:  
  push:    
    branches:      
      - main
permissions:  
  contents: write
jobs:  
  deploy:    
    runs-on: ubuntu-latest    
    steps:     
       - uses: actions/checkout@v4        
        with:           
          fetch-depth: 0      
       - uses: actions/setup-python@v4        
        with:          
          python-version: 3.11            
       - name: Install pipenv        
        run: pip install pipenv      
       - name: Install dependencies using pipenv        
        run: pipenv install --deploy --system      
       - name: Run mkdocs gh-deploy        
        run: pipenv run mkdocs gh-deploy --force